using System.ComponentModel.DataAnnotations;

namespace Foundation.Web.Models;

/// <summary>
/// A kiosk display registered to this site. A kiosk enrolls itself: a device
/// that opens /Kiosk without a known device id runs the on-screen setup wizard,
/// picks its scale, printer and card reader from what the site actually has
/// connected, and saves a row here. Everything after that comes from the
/// server, so a kiosk URL is just the server address — nothing to key in, and
/// nothing to lose when a bookmark is retyped.
///
/// Hardware is named the way <see cref="Scale"/> names it: "serviceId:thingId"
/// as reported by the connected device services. Null means "this kiosk has
/// none", which is a legitimate answer for both the printer and the reader —
/// the setup wizard offers Skip for each.
/// </summary>
public class Kiosk
{
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// Identity of the physical device, generated by the browser on first run
    /// and held in a cookie (mirrored to localStorage). Opaque and unique; a
    /// device that loses it is simply an unregistered kiosk and sets itself up
    /// again.
    /// </summary>
    [Required]
    [StringLength(64)]
    [Display(Name = "Device")]
    public string DeviceId { get; set; } = "";

    /// <summary>Human label shown on the Kiosks page and in the kiosk's corner
    /// ("North Inbound"). Auto-named at enrollment — a kiosk has no keyboard —
    /// and renamed from the web app.</summary>
    [Required]
    [StringLength(100)]
    [Display(Name = "Kiosk Name")]
    public string Name { get; set; } = "";

    /// <summary>Site scale this kiosk weighs on. Null falls back to the default
    /// (first active) scale, which is what a single-scale site wants.</summary>
    [Display(Name = "Scale")]
    public int? ScaleId { get; set; }

    /// <summary>Ticket printer as "serviceId:printerId", or "Browser:Browser"
    /// to print through the kiosk's own browser. Null means this kiosk prints
    /// nothing — the driver's ticket is handled elsewhere.</summary>
    [StringLength(100)]
    [Display(Name = "Printer")]
    public string? PrinterId { get; set; }

    /// <summary>Card reader as "serviceId:readerId". Null means this kiosk
    /// ignores card presentations and runs the touchscreen flow.</summary>
    [StringLength(100)]
    [Display(Name = "Card Reader")]
    public string? ReaderId { get; set; }

    /// <summary>Inactive kiosks stay on the list but are treated as
    /// unregistered, so the device sets itself up again on next load.</summary>
    [Display(Name = "Active")]
    public bool Active { get; set; } = true;

    [Display(Name = "Registered")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Last time this device loaded the kiosk page. The Kiosks page
    /// reads it to tell a live kiosk from one that was unplugged months ago.</summary>
    [Display(Name = "Last Seen")]
    public DateTime? LastSeenAt { get; set; }
}
